name = "域名监控"    
main = "src/index.js"
compatibility_date = "2025-11-17"  
keep_vars = true

[[芒果的域名]]    
binding = "DOMAIN_KV"   
id = "78be3f233d674adabda703afb9589af6" # 替换成你实际的 KV ID                  

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
